name: migration-boilerplate
recipe: drupal8
config:
  via: nginx
  webroot: web
  php: 7.2
  database: mariadb

services:
  d7db:
    type: mariadb
    creds:
      user: drupal7db
      password: drupal7db
      database: drupal7db
    portforward: true
